name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no . username@ec2-ip-address:/path/on/ec2

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no username@ec2-ip-address << 'EOF'
          cd /path/on/ec2/to/your/project
          sudo docker-compose down
          sudo docker-compose up --build -d
        EOF
